import type { Metadata } from 'next'
import { Suspense } from 'react'
import { ReduxProvider } from '@/redux/provider'

// [publish]
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import '@styles/fonts/pretendard.css'
import { Flowbite } from 'flowbite-react';
import theme from '@styles/theme'

// [Layout]
import Navbar from '@/layout/Navbar';
import Footer from '@/layout/Footer';

// [Common Components]
import Script from 'next/script'
import Toast from '@/components/Toast/ToastModal'
import AlertDialog from '@/components/Alert/AlertDialog'
import ConfirmDialog from '@/components/Alert/ConfirmDialog'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png"/>
      <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png"/>
      <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png"/>
      <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png"/>
      <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png"/>
      <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png"/>
      <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png"/>
      <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png"/>
      <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png"/>
      <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png"/>
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png"/>
      <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png"/>
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png"/>



      <body className='text-lato'>
        <Flowbite theme={{ theme }}>
          <ReduxProvider>
            <Navbar />
            {children}
            <Footer />

            <Toast />
            <AlertDialog />
            <ConfirmDialog />

          </ReduxProvider>
        </Flowbite>
        {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.17/paper-full.min.js" /> */}
      </body>
    </html>
  )
}
